# _config.yml
theme: minima
title: Brent Passmore
author: Brent Passmore
description: The guy you need to know when you need to know a guy.
baseurl: ""
url: ""
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
show_excerpts: true
google_analytics: G-TWQSE4V8P2
collections:
  categories:
    output: true
social:
  bluesky: "https://bsky.app/profile/brent.bsky.social"
  facebook: "https://facebook.com/brentpassmore"
  github: "https://github.com/bpmore"
  x: "https://x.com/bpmore"